#!/usr/bin/env bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${PAYLOAD_PGUSER} WITH PASSWORD '${PAYLOAD_PGPASSWORD}';
	CREATE DATABASE ${PAYLOAD_PGDATABASE};
	GRANT ALL PRIVILEGES ON DATABASE ${PAYLOAD_PGDATABASE} TO ${PAYLOAD_PGUSER};
    \c ${PAYLOAD_PGDATABASE} ${POSTGRES_USER}
    GRANT ALL ON SCHEMA public TO ${PAYLOAD_PGUSER};
EOSQL

